# Configuracion de controladores de posicion
puma560:
  # Joint State controller 
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50   # 50 Hz

  # Trajectory Controller
  arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - joint_base_to_waist
      - joint_waist_to_shoulder
      - joint_shoulder_to_elbow
      - joint_elbow_to_wrist_bend
      - joint_wrist_bend_to_roll
    gain:
      joint_base_to_waist: {p: 100.00, i: 0.01, d: 10.0 }
      joint_waist_to_shoulder: {p: 100.00, i: 0.01, d: 10.0 }
      joint_shoulder_to_elbow: {p: 100.00, i: 0.01, d: 10.0 }
      joint_elbow_to_wrist_bend: {p: 100.00, i: 0.01, d: 10.0 }
      joint_wrist_bend_to_roll: {p: 100.00, i: 0.01, d: 10.0 }
